### ISSUE TITLE
python crash if producers is not defined

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/maestro#23]
In the case where there is no updtr/prdcr stuff needed (and hence not included in the input yaml) maestro_ctrl crashes.  In this case, the worst that maestro_ctrl should do is issue a short warning that no updater/producer information was found and then continue processing.
```
  File "./maestro_ctrl", line 591, in <module>
    cluster = Cluster(client, args.prefix, conf_spec)
  File "./maestro_ctrl", line 309, in __init__
    self.producers = self.build_producers(cluster_config)
  File "./maestro_ctrl", line 164, in build_producers
    prod_spec = config['producers']
KeyError: 'producers'
```

**Comment by baallan** [comment]
Same goes for updaters key.

**Comment by nick-enoent** [comment]
@baallan Please see commit 932b5c20b00fc617a2787b6de40f6df92d07af50

**Comment by baallan** [comment]
resolved. thanks.
