### ISSUE TITLE
int parameters not handled in cvt_intrvl_str_to_us

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/maestro#24]
maestro_ctrl:535 assumes the input is a string. yaml may produce an int or float in this position of the tree, leading to a crash.

**Comment by baallan** [comment]
same applies to maestro cvt_intrvl_str_to_us

**Comment by baallan** [comment]
@tom95858 I haven't seen the requirement of "float+units" only in any meeting minutes nor remember it from the conversation. I certainly never agreed to it. Since for all of ldms history these time parameters have been unitless microseconds, it doesn't seem a stretch to me to continue supporting unitless microsecond int values and to add the option of a unit-ed string value. @morrone @valleydlr would you concur with me or with Tom?

**Comment by valleydlr** [comment]
@baallan My recollection is that we all agreed to the float with units nomenclature for Maestro at the prior users group meeting.

**Comment by morrone** [comment]
cvt_intrvl_str_to_us() really needs to perform proper input validation, if that isn't happening elsewhere. It looks to me like that function would happily interpret "40us30" as "4030 microseconds". That should really result in a parsing error.

I'm not sure that I agree that the old configuration needs to support all of the formats that the new maestro files can handle. I think it is perfectly reasonably for the maestro format to add additional sugar like human-readable time formats without the underlying API knowing about those details. And the old "configuration format" is mostly just a thin wrapper around the API.

Ideally anyone starting out with the "new yaml ldms" would never need to know that the old format exists. We probably failed some where if they do.
