### ISSUE TITLE
domain residual needs to be removed?

### ISSUE THREAD

**Issue by baallan** [ovis-hpc/maestro#31]
The maestro readme describes 'domain' and 'config' in some stanzas.
It appears none of this is used anywhere.
Can we remove it from the examples/readme?

**Comment by baallan** [comment]
@nick-enoent If I made a patch for this, would you take it?

**Comment by tom95858** [comment]
@baallan, we will update the readme when we release the updated YAML syntax. This should happen in the next week...

**Comment by baallan** [comment]
good enough
