### ISSUE TITLE
Eliminate "producers" section?

### ISSUE THREAD

**Issue by morrone** [ovis-hpc/maestro#6]
Can we perhaps eliminate the "producers" section entirely in the new configuration system?

We more-or-less needed "producers" in the old system because we did _not_ list the configuration details for each of the other nodes in the old format. But with the new yaml, we do have that information for the rest of the nodes in the cluster. So perhaps we can start abstract away implementation details like "producers" and "updaters" and instead focus on configuring what we want to happen.

**Comment by tom95858** [comment]
I really like this idea.

**Comment by oceandlr** [comment]
If this is about "producer" being a field in the meta-data, the case where it has been really necessary is when reading the aries router data from a node. The component id is the reporting node, but the producer is the router. 2 or 4 nodes per router, depending on if service or compute node. It would be bad if we can't still represent that.

**Comment by tom95858** [comment]
This is about the maestro configuration file format and if the 'producer' section of that file is in fact redundant and unnecessary.
